import { useEffect, useState } from 'react'
import { Link, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowRight, ShieldCheck, Truck, Headphones, PackageCheck, Plus, Trash2 } from 'lucide-react'
import { authApi, cartApi, catalogApi, type ApiCategory, type ApiProduct, type Cart } from '../api/client'
import { SiteHeader } from '../components/SiteHeader'
import { ProductCard } from '../components/ProductCard'
import type { Product } from '../types'

const toProduct = (p: ApiProduct): Product => ({ ...p, price: p.selling_price ?? p.price ?? 0, image: p.images?.[0] || p.image_url || undefined, category: p.category_name ?? p.category, description: p.short_description ?? p.description })
const ErrorState = ({ message }: { message: string }) => <div className="empty-state large">{message}</div>

function Home() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<ApiCategory[]>([]); const [error, setError] = useState('')
  useEffect(() => { Promise.all([catalogApi.products('page_size=4'), catalogApi.categories()]).then(([p, c]) => { setProducts((p.items || []).map(toProduct)); setCategories(Array.isArray(c) ? c : []) }).catch(e => setError(e.message)) }, [])
  return <><section className="hero"><div className="hero-copy"><p className="eyebrow light">The hardware store, made easier</p><h1>Build better.<br/><em>Fix faster.</em></h1><p className="hero-text">Reliable plumbing, sanitation and hardware supplies for homes, pros and every project in between.</p><div className="hero-actions"><Link className="button button-light" to="/shop">Explore products <ArrowRight size={17}/></Link><Link className="text-link light" to="/shop?category=plumbing">Shop plumbing <ArrowRight size={15}/></Link></div></div><div className="hero-art"><div className="hero-shape shape-one"/><div className="hero-shape shape-two"/><span className="hero-label">01 / 03<br/><b>Built for every fix</b></span></div></section><section className="trust-row"><div><Truck/><span><b>Fast delivery</b><small>Across India</small></span></div><div><ShieldCheck/><span><b>Genuine products</b><small>Quality assured</small></span></div><div><Headphones/><span><b>Expert support</b><small>Here when you need us</small></span></div><div><PackageCheck/><span><b>Bulk pricing</b><small>For every trade</small></span></div></section><section className="section"><div className="section-heading"><div><p className="eyebrow">Shop by need</p><h2>Everything for the job.</h2></div><Link className="text-link" to="/shop">View all <ArrowRight size={15}/></Link></div><div className="category-grid">{categories.slice(0, 4).map((c, i) => <Link to={`/shop?category=${encodeURIComponent(c.slug || c.name)}`} className={`category-card category-${i + 1}`} key={c.id}><span>0{i + 1}</span><h3>{c.name}</h3><ArrowRight size={18}/></Link>)}</div>{error && <ErrorState message={error}/>}</section><section className="section featured"><div className="section-heading"><div><p className="eyebrow">Popular picks</p><h2>Good gear, ready to go.</h2></div><Link className="text-link" to="/shop">See catalog <ArrowRight size={15}/></Link></div><div className="product-grid">{products.map(p => <ProductCard key={p.id} product={p} onAdd={id => cartApi.add(id).catch(e => alert(e.message))}/>)}</div></section></>
}

function Shop() { const [params] = useSearchParams(); const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const search = params.get('search') || ''; const category = params.get('category') || ''; useEffect(() => { setLoading(true); setError(''); catalogApi.products(new URLSearchParams({ page_size: '40', ...(search && { search }), ...(category && { category }) }).toString()).then(p => setProducts((p.items || []).map(toProduct))).catch(e => { setProducts([]); setError(e.message) }).finally(() => setLoading(false)) }, [search, category]); return <section className="shop-page section"><div className="shop-header"><div><p className="eyebrow">Catalog / {category || 'All products'}</p><h1>{search ? `Results for “${search}”` : 'Shop all hardware'}</h1><p className="muted">Live products, prices and availability from the LUVIIO catalog.</p></div></div>{loading ? <div className="loading">Loading the catalog…</div> : error ? <ErrorState message={error}/> : products.length ? <div className="product-grid">{products.map(p => <ProductCard key={p.id} product={p} onAdd={id => cartApi.add(id).catch(e => alert(e.message))}/>)}</div> : <div className="empty-state large">No products found. Try another search or category.</div>}</section> }

function ProductDetail() { const { slug = '' } = useParams(); const [product, setProduct] = useState<Product | null>(null); const [error, setError] = useState(''); const [added, setAdded] = useState(false); useEffect(() => { catalogApi.product(slug).then(p => setProduct(toProduct(p))).catch(e => setError(e.message)) }, [slug]); if (error) return <section className="placeholder section"><ErrorState message={error}/></section>; if (!product) return <section className="placeholder section"><div className="loading">Loading product…</div></section>; return <section className="product-detail section"><Link className="text-link" to="/shop">← Back to catalog</Link><div className="detail-grid"><div className="detail-image">{product.image ? <img src={product.image} alt={product.name}/> : <span>{product.category?.slice(0, 1) || 'L'}</span>}</div><div><p className="eyebrow">{product.category || 'Hardware'}</p><h1>{product.name}</h1><p className="detail-price">₹{product.price.toLocaleString('en-IN')}</p><p className="muted">{product.description || 'Reliable hardware for professional and home projects.'}</p><p className="stock">{product.stock_status || 'Availability verified at checkout'}</p><button className="button button-dark" onClick={() => cartApi.add(product.id).then(() => setAdded(true)).catch(e => alert(e.message))}>{added ? 'Added to cart' : 'Add to cart'} <Plus size={17}/></button></div></div></section> }

function CartPage() { const [cart, setCart] = useState<Cart | null>(null); const [error, setError] = useState(''); useEffect(() => { cartApi.get().then(setCart).catch(e => setError(e.message)) }, []); if (error) return <section className="placeholder section"><ErrorState message={`${error}. Please sign in to view your cart.`}/><Link className="button button-dark" to="/account">Sign in</Link></section>; return <section className="cart-page section"><p className="eyebrow">Your basket</p><h1>Cart</h1>{!cart?.items?.length ? <div className="empty-state large">Your cart is empty. <Link to="/shop">Browse products</Link></div> : <div className="cart-list">{cart.items.map(item => <div className="cart-line" key={item.product_id}><span>{item.product?.name || item.product_id}</span><span>Qty {item.quantity}</span><strong>₹{(item.total ?? item.unit_price ?? 0).toLocaleString('en-IN')}</strong><button aria-label="Remove item" onClick={() => cartApi.remove(item.product_id).then(setCart)}><Trash2 size={17}/></button></div>)}<div className="cart-total"><span>Total</span><strong>₹{(cart.total ?? cart.subtotal ?? 0).toLocaleString('en-IN')}</strong></div><Link className="button button-dark" to="/account">Continue to checkout <ArrowRight size={17}/></Link></div>}</section> }

function Account() { const [session, setSession] = useState<{ authenticated: boolean; email?: string } | null>(null); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); useEffect(() => { authApi.session().then(setSession).catch(() => setSession({ authenticated: false })) }, []); const submit = (e: React.FormEvent) => { e.preventDefault(); authApi.login({ email, password }).then(() => { setSession({ authenticated: true, email }); setMessage('Signed in successfully.') }).catch(e => setMessage(e.message)) }; if (session?.authenticated) return <section className="placeholder section"><p className="eyebrow">Account</p><h1>Welcome back.</h1><p>{session.email}</p><button className="button button-dark" onClick={() => authApi.logout().then(() => setSession({ authenticated: false }))}>Sign out</button></section>; return <section className="auth-page section"><p className="eyebrow">LUVIIO account</p><h1>Sign in to continue.</h1><form className="auth-form" onSubmit={submit}><label>Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)}/></label><label>Password<input required type="password" value={password} onChange={e => setPassword(e.target.value)}/></label><button className="button button-dark" type="submit">Sign in <ArrowRight size={17}/></button>{message && <p className="muted">{message}</p>}</form></section> }

function Placeholder({ title, copy }: { title: string; copy: string }) { return <section className="placeholder section"><p className="eyebrow">Luviio</p><h1>{title}</h1><p>{copy}</p><Link className="button button-dark" to="/shop">Continue shopping <ArrowRight size={17}/></Link></section> }
export default function App() { return <><SiteHeader/><main><Routes><Route path="/" element={<Home/>}/><Route path="/shop" element={<Shop/>}/><Route path="/product/:slug" element={<ProductDetail/>}/><Route path="/cart" element={<CartPage/>}/><Route path="/account" element={<Account/>}/><Route path="*" element={<Placeholder title="Page not found" copy="The page you’re looking for doesn’t exist."/>}/></Routes></main><footer><div className="brand"><span className="brand-mark">L</span><span>luviio<span className="brand-dot">.</span></span></div><p>Hardware that works as hard as you do.</p><span>© 2026 Luviio.in</span></footer></> }
