import { useEffect, useState } from 'react'
import { Link, Route, Routes, useSearchParams } from 'react-router-dom'
import { ArrowRight, ShieldCheck, Truck, Headphones, PackageCheck, SlidersHorizontal } from 'lucide-react'
import { catalogApi, cartApi, type ApiCategory, type ApiProduct } from '../api/client'
import { SiteHeader } from '../components/SiteHeader'
import { ProductCard } from '../components/ProductCard'
import type { Product } from '../types'

const toProduct = (p: ApiProduct): Product => ({ id:p.id, name:p.name, slug:p.slug, price:p.selling_price ?? p.price ?? 0, image:p.images?.[0], category:p.category, description:p.short_description, stock_status:p.stock_status })

function Home() { const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<ApiCategory[]>([]); const [error,setError]=useState(''); useEffect(()=>{Promise.all([catalogApi.products('page_size=4'),catalogApi.categories()]).then(([p,c])=>{setProducts(p.items.map(toProduct));setCategories(c)}).catch(e=>setError(e.message))},[]); return <><section className="hero"><div className="hero-copy"><p className="eyebrow light">The hardware store, made easier</p><h1>Build better.<br/><em>Fix faster.</em></h1><p className="hero-text">Reliable plumbing, sanitation and hardware supplies for homes, pros and every project in between.</p><div className="hero-actions"><Link className="button button-light" to="/shop">Explore products <ArrowRight size={17}/></Link><Link className="text-link light" to="/shop?category=plumbing">Shop plumbing <ArrowRight size={15}/></Link></div></div><div className="hero-art"><div className="hero-shape shape-one"/><div className="hero-shape shape-two"/><span className="hero-label">01 / 03<br/><b>Built for every fix</b></span></div></section><section className="trust-row"><div><Truck/><span><b>Fast delivery</b><small>Across India</small></span></div><div><ShieldCheck/><span><b>Genuine products</b><small>Quality assured</small></span></div><div><Headphones/><span><b>Expert support</b><small>Here when you need us</small></span></div><div><PackageCheck/><span><b>Bulk pricing</b><small>For every trade</small></span></div></section><section className="section"><div className="section-heading"><div><p className="eyebrow">Shop by need</p><h2>Everything for the job.</h2></div><Link className="text-link" to="/shop">View all <ArrowRight size={15}/></Link></div><div className="category-grid">{categories.slice(0,4).map((c,i)=><Link to={`/shop?category=${c.slug||c.name}`} className={`category-card category-${i+1}`} key={c.id}><span>0{i+1}</span><h3>{c.name}</h3><ArrowRight size={18}/></Link>)}{!categories.length&&<p className="empty-state">Categories will appear here once the catalog is connected.</p>}</div></section><section className="section products-section"><div className="section-heading"><div><p className="eyebrow">Popular picks</p><h2>Good tools. Fair prices.</h2></div><Link className="text-link" to="/shop">Browse catalog <ArrowRight size={15}/></Link></div>{error?<p className="error-state">Unable to load catalog: {error}</p>:<div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>}</section><section className="trade-banner"><div><p className="eyebrow light">For contractors & businesses</p><h2>Buying more?<br/><em>Save more.</em></h2><p>Get tailored pricing and dedicated support for your next project.</p></div><Link className="button button-light" to="/account">Talk to our team <ArrowRight size={17}/></Link></section></> }

function Shop() { const [params]=useSearchParams(); const [products,setProducts]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const search=params.get('search')||''; const category=params.get('category')||''; useEffect(()=>{setLoading(true);catalogApi.products(new URLSearchParams({page_size:'40',...(search&&{search}),...(category&&{category})}).toString()).then(p=>setProducts(p.items.map(toProduct))).catch(()=>setProducts([])).finally(()=>setLoading(false))},[search,category]); return <section className="shop-page section"><div className="shop-header"><div><p className="eyebrow">Catalog / {category||'All products'}</p><h1>{search?`Results for “${search}”`:'Shop all hardware'}</h1><p className="muted">Built for homeowners, professionals and growing businesses.</p></div><button className="filter-button"><SlidersHorizontal size={17}/> Filters</button></div>{loading?<div className="loading">Loading the catalog…</div>:products.length?<div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty-state large">No products found. Try another search or category.</div>}</section> }
function Placeholder({title,copy}:{title:string;copy:string}){return <section className="placeholder section"><p className="eyebrow">Luviio</p><h1>{title}</h1><p>{copy}</p><Link className="button button-dark" to="/shop">Continue shopping <ArrowRight size={17}/></Link></section>}
export default function App(){return <><SiteHeader/><main><Routes><Route path="/" element={<Home/>}/><Route path="/shop" element={<Shop/>}/><Route path="/product/:slug" element={<Placeholder title="Product details" copy="Product detail and add-to-cart actions are connected to the catalog API."/>}/><Route path="/cart" element={<Placeholder title="Your cart" copy="Your server-side cart will appear here after sign in."/>}/><Route path="/account" element={<Placeholder title="Your Luviio account" copy="Sign in to manage orders, addresses and trade pricing."/>}/><Route path="*" element={<Placeholder title="Page not found" copy="The page you’re looking for doesn’t exist."/>}/></Routes></main><footer><div className="brand"><span className="brand-mark">L</span><span>luviio<span className="brand-dot">.</span></span></div><p>Hardware that works as hard as you do.</p><span>© 2026 Luviio.in</span></footer></>}
