import { Link, useNavigate } from 'react-router-dom'
import { Search, ShoppingCart, UserRound, Menu, X, ChevronDown } from 'lucide-react'
import { useState } from 'react'

export function SiteHeader() {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const navigate = useNavigate()
  const submit = (e: React.FormEvent) => { e.preventDefault(); navigate(`/shop?search=${encodeURIComponent(query)}`) }
  return <><div className="announcement">Trade pricing available on bulk orders <span>·</span> Free delivery above ₹2,500</div><header className="header"><Link to="/" className="brand"><span className="brand-mark">L</span><span>luviio<span className="brand-dot">.</span></span></Link><form className="search" onSubmit={submit}><Search size={18}/><input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pipes, taps, tools..."/><kbd>⌘ K</kbd></form><nav className="desktop-nav"><Link to="/shop">Shop</Link><Link to="/shop?category=plumbing">Plumbing</Link><Link to="/shop?category=sanitation">Sanitation</Link><Link to="/account">Account</Link></nav><div className="header-actions"><Link to="/account" aria-label="Account"><UserRound size={20}/></Link><Link to="/cart" aria-label="Cart" className="cart-link"><ShoppingCart size={20}/><span>0</span></Link><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div></header>{open&&<div className="mobile-nav"><Link to="/shop" onClick={()=>setOpen(false)}>Shop <ChevronDown size={16}/></Link><Link to="/shop?category=plumbing" onClick={()=>setOpen(false)}>Plumbing</Link><Link to="/shop?category=sanitation" onClick={()=>setOpen(false)}>Sanitation</Link><Link to="/account" onClick={()=>setOpen(false)}>Account</Link></div>}</>
}
